apiVersion: v1
kind: Service
metadata:
  name: hello-world-service
  namespace: default
spec:
  selector:
    deployment: hello-world
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 80
