apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-alt-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: hello-alt
  template:
    metadata:
      labels:
        deployment: hello-alt
    spec:
      containers:
      - name: hello-world-alt-container
        image: monopole/hello:1
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        command: ["/hello",
                  "--port=8080",
                  "--enableRiskyFeature=$(ENABLE_RISKY)"]
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
        ports:
        - containerPort: 8080
        env:
        - name: ALT_GREETING
          valueFrom:
            configMapKeyRef:
              name: hello-world-alt-map
              key: altGreeting
        - name: ENABLE_RISKY
          valueFrom:
            configMapKeyRef:
              name: hello-world-alt-map
              key: enableRisky
