apiVersion: v1
kind: Service
metadata:
  name: hello-world-alt-service
  namespace: default
spec:
  selector:
    deployment: hello
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8080
